#!/bin/sh
apt-get -y install emacs24 ruby1.9.1 libruby1.9.1 ri1.9.1 ruby1.9.1-dev
apt-get -y install libmagickwand-dev libxml2-dev libxslt1-dev nodejs libsasl2-dev
apt-get -y install apache2 apache2-threaded-dev build-essential git-core
apt-get -y install postgresql  postgresql-contrib libpq-dev postgresql-server-dev-all
apt-get -y install osmosis
gem1.9.1 install bundler
